

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "ScenarioList.xaml.h"




void ::SDKSample::ScenarioList::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///ScenarioList.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///ScenarioList.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'RootGrid'
    RootGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"RootGrid"));
    // Get the StackPanel named 'TitlePanel'
    TitlePanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"TitlePanel"));
    // Get the Grid named 'ContentPanel'
    ContentPanel = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ContentPanel"));
    // Get the ListBox named 'ScenarioControl'
    ScenarioControl = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ScenarioControl"));
    // Get the StackPanel named 'FooterPanel'
    FooterPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"FooterPanel"));
    // Get the TextBlock named 'SampleTitle'
    SampleTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SampleTitle"));
}

void ::SDKSample::ScenarioList::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::SDKSample::ScenarioList::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&ScenarioList::ScenarioControl_SelectionChanged);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::ScenarioList::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ScenarioList::Footer_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::ScenarioList::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ScenarioList::Footer_Click);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::ScenarioList::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ScenarioList::Footer_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

