

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBlock;
                ref class Slider;
                ref class TextBox;
                ref class Button;
                ref class Image;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}

namespace SDKSample
{
    namespace ListViewSimple
    {
        partial ref class Scenario4 : public ::Windows::UI::Xaml::Controls::Page, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
        
            private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
            private: ::Windows::UI::Xaml::Controls::Grid^ Input;
            private: ::Windows::UI::Xaml::Controls::Grid^ Output;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ PointsBlock;
            private: ::Windows::UI::Xaml::Controls::Slider^ Selector;
            private: ::Windows::UI::Xaml::Controls::Slider^ FlipSwitch;
            private: ::Windows::UI::Xaml::Controls::TextBox^ inputBox_Real;
            private: ::Windows::UI::Xaml::Controls::TextBox^ inputBox_Imaginary;
            private: ::Windows::UI::Xaml::Controls::Button^ FindFFTButton;
            private: ::Windows::UI::Xaml::Controls::Image^ outputImage;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input80;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input81;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input82;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input83;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input84;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input85;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input86;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input87;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt80;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt81;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt82;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt83;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt84;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt85;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt86;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt87;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt40;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt41;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt42;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt43;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt44;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt45;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt46;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt47;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt20;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt21;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt22;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt23;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt24;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt25;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt26;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ pt27;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input40;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input41;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input42;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input43;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _4pt0;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _4pt1;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _4pt2;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _4pt3;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _2pt0;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _2pt1;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _2pt2;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _2pt3;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input20;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ Input21;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _2Out0;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ _2Out1;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ InputTextBlock1;
            private: ::Windows::UI::Xaml::VisualState^ InputDefaultLayout;
            private: ::Windows::UI::Xaml::VisualState^ InputBelow768Layout;
        };
    }
}

